version: "2.0"

services:
  ucan-store:
    image: ghcr.io/nomadkids/ucan-store-akash:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - UCAN_STORE_PUBLIC_ORIGIN=
      - UCAN_STORE_DATA_DIR=/data/ucan-store
      - IPFS_PATH=/data/ipfs

profiles:
  compute:
    ucan-store:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 10Gi
  placement:
    dcloud:
      pricing:
        ucan-store:
          denom: uact
          amount: 1000

deployment:
  ucan-store:
    dcloud:
      profile: ucan-store
      count: 1
